
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = b'\xd0\x1e\x13\xeb\xf1\xda\x19u\xd9\xe0\xfe\x16\x92\xf4h\xd7'
    
_lr_action_items = {'&':([1,2,3,4,5,6,8,9,10,12,13,14,24,25,26,32,34,35,36,],[-11,-12,-4,17,-14,-13,-5,-8,-15,-18,-16,-10,-20,-19,-17,-3,-6,-7,-9,]),'SQUOTE_LITERAL':([0,1,2,5,6,10,11,12,13,14,15,16,17,20,21,22,23,24,25,26,27,28,29,30,33,],[5,5,-12,-14,-13,-15,5,-18,-16,5,-24,-24,-25,-26,5,-21,-24,-20,-19,-17,5,-23,5,-22,5,]),'DQUOTE_LITERAL':([0,1,2,5,6,10,11,12,13,14,15,16,17,20,21,22,23,24,25,26,27,28,29,30,33,],[6,6,-12,-14,-13,-15,6,-18,-16,6,-24,-24,-25,-26,6,-21,-24,-20,-19,-17,6,-23,6,-22,6,]),'OR':([1,2,3,5,6,8,9,10,12,13,14,24,25,26,32,34,35,36,],[-11,-12,16,-14,-13,-5,-8,-15,-18,-16,-10,-20,-19,-17,16,-6,-7,-9,]),';':([1,2,3,4,5,6,8,9,10,12,13,14,24,25,26,32,34,35,36,],[-11,-12,-4,20,-14,-13,-5,-8,-15,-18,-16,-10,-20,-19,-17,-3,-6,-7,-9,]),'REDIRECT':([1,2,5,6,10,12,13,14,24,25,26,],[11,-12,-14,-13,-15,-18,-16,11,-20,-19,-17,]),'|':([1,2,5,6,8,9,10,12,13,14,24,25,26,34,35,36,],[-11,-12,-14,-13,23,-8,-15,-18,-16,-10,-20,-19,-17,23,23,-9,]),'WORD_LITERAL':([0,1,2,5,6,10,11,12,13,14,15,16,17,20,21,22,23,24,25,26,27,28,29,30,33,],[2,2,-12,-14,-13,-15,2,-18,-16,2,-24,-24,-25,-26,2,-21,-24,-20,-19,-17,2,-23,2,-22,2,]),'NEWLINE':([1,2,3,4,5,6,8,9,10,12,13,14,15,16,17,19,20,21,22,23,24,25,26,28,30,32,34,35,36,],[-11,-12,-4,22,-14,-13,-5,-8,-15,-18,-16,-10,22,22,-25,30,-26,22,-21,22,-20,-19,-17,30,-22,-3,-6,-7,-9,]),'AND':([1,2,3,5,6,8,9,10,12,13,14,24,25,26,32,34,35,36,],[-11,-12,15,-14,-13,-5,-8,-15,-18,-16,-10,-20,-19,-17,15,-6,-7,-9,]),'$end':([1,2,3,4,5,6,7,8,9,10,12,13,14,17,18,19,20,21,22,24,25,26,28,30,31,32,34,35,36,],[-11,-12,-4,-2,-14,-13,0,-5,-8,-15,-18,-16,-10,-25,-1,-28,-26,-24,-21,-20,-19,-17,-23,-22,-27,-3,-6,-7,-9,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'cmd_name':([0,21,27,29,33,],[1,1,1,1,1,]),'separator':([4,],[18,]),'newline_list':([4,15,16,21,23,],[19,28,28,28,28,]),'linebreak':([15,16,21,23,],[27,29,31,33,]),'and_or':([0,21,],[3,32,]),'io_redirect':([1,14,],[13,26,]),'list':([0,],[4,]),'complete_command':([0,],[7,]),'pipeline':([0,21,27,29,],[8,8,34,35,]),'command':([0,21,27,29,33,],[9,9,9,9,36,]),'word':([0,1,11,14,21,27,29,33,],[10,12,24,25,10,10,10,10,]),'cmd_suffix':([1,],[14,]),'separator_op':([4,],[21,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> complete_command","S'",1,None,None,None),
  ('complete_command -> list separator','complete_command',2,'p_complete_command','PySH/parser.py',104),
  ('complete_command -> list','complete_command',1,'p_complete_command','PySH/parser.py',105),
  ('list -> list separator_op and_or','list',3,'p_list','PySH/parser.py',111),
  ('list -> and_or','list',1,'p_list','PySH/parser.py',112),
  ('and_or -> pipeline','and_or',1,'p_and_or','PySH/parser.py',119),
  ('and_or -> and_or AND linebreak pipeline','and_or',4,'p_and_or','PySH/parser.py',120),
  ('and_or -> and_or OR linebreak pipeline','and_or',4,'p_and_or','PySH/parser.py',121),
  ('pipeline -> command','pipeline',1,'p_pipeline','PySH/parser.py',130),
  ('pipeline -> pipeline | linebreak command','pipeline',4,'p_pipeline','PySH/parser.py',131),
  ('command -> cmd_name cmd_suffix','command',2,'p_command','PySH/parser.py',139),
  ('command -> cmd_name','command',1,'p_command','PySH/parser.py',140),
  ('word -> WORD_LITERAL','word',1,'p_word','PySH/parser.py',147),
  ('word -> DQUOTE_LITERAL','word',1,'p_word','PySH/parser.py',148),
  ('word -> SQUOTE_LITERAL','word',1,'p_word','PySH/parser.py',149),
  ('cmd_name -> word','cmd_name',1,'p_cmd_name','PySH/parser.py',153),
  ('cmd_suffix -> io_redirect','cmd_suffix',1,'p_cmd_suffix','PySH/parser.py',157),
  ('cmd_suffix -> cmd_suffix io_redirect','cmd_suffix',2,'p_cmd_suffix','PySH/parser.py',158),
  ('cmd_suffix -> word','cmd_suffix',1,'p_cmd_suffix','PySH/parser.py',159),
  ('cmd_suffix -> cmd_suffix word','cmd_suffix',2,'p_cmd_suffix','PySH/parser.py',160),
  ('io_redirect -> REDIRECT word','io_redirect',2,'p_io_redirect','PySH/parser.py',175),
  ('newline_list -> NEWLINE','newline_list',1,'p_newline_list','PySH/parser.py',180),
  ('newline_list -> newline_list NEWLINE','newline_list',2,'p_newline_list','PySH/parser.py',181),
  ('linebreak -> newline_list','linebreak',1,'p_linebreak','PySH/parser.py',185),
  ('linebreak -> <empty>','linebreak',0,'p_linebreak','PySH/parser.py',186),
  ('separator_op -> &','separator_op',1,'p_separator_op','PySH/parser.py',190),
  ('separator_op -> ;','separator_op',1,'p_separator_op','PySH/parser.py',191),
  ('separator -> separator_op linebreak','separator',2,'p_separator','PySH/parser.py',195),
  ('separator -> newline_list','separator',1,'p_separator','PySH/parser.py',196),
]
