#!/usr/bin/env python3

from PySH.shell import Shell


if __name__ == '__main__':
    import argparse

    parser = argparse.ArgumentParser()

    args = parser.parse_args()

    with Shell() as sh:
        sh.run_interactive()

